### ISSUE TITLE
Flow diagram

### ISSUE THREAD

**Issue by vivekka93** [airavata-courses/PixelSquad#2]

**Comment by vivekka93** [comment]
User journey:
User signup -> Login -> Upload images -> View image(s) -> Download image(s) -> Share image(s) -> Search for image(s) -> Organize images into folders -> Edit profile/ remove account

Following could be the activities of users:

![IMG_20210204_124344](https://user-images.githubusercontent.com/19610087/106933476-f4c51500-66e6-11eb-94cc-0ea2b818d8d9.jpg)

![IMG_20210204_124402](https://user-images.githubusercontent.com/19610087/106933544-0c040280-66e7-11eb-89ba-a453ba7b85d6.jpg)
![IMG_20210204_124416](https://user-images.githubusercontent.com/19610087/106933600-1a521e80-66e7-11eb-973f-deaab3b74088.jpg)

**Comment by vivekka93** [comment]
First draft of the info architecture diagram
![flowchart](https://user-images.githubusercontent.com/19610087/106974306-7e460880-6722-11eb-9135-facc4ecbb1e2.jpg)

Please suggest any changes/ additions

**Comment by danagar0312** [comment]
looks good. messaging queue behaves as API gateway in our architecture diagram.
