### ISSUE TITLE
Git branching strategy

### ISSUE THREAD

**Issue by vivekka93** [airavata-courses/PixelSquad#4]

**Comment by danagar0312** [comment]
Need to have dev branch that will have merge approval in settings for either of the other two members

**Comment by vivekka93** [comment]
As per the discussion today, we will be having dev branch as main branch for development work and master branch to maintain release versions. Each pull request has to be approved by at least one other team member.

**Comment by SahibaM** [comment]
2 branches will be maintained for development and release work.
